name: GHCR Cleanup
on:
  schedule:
    - cron: "20 4 * * sun" # every Sunday at 4:20 AM UTC
  workflow_dispatch:
permissions:
  packages: write
jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f
