name: GHCR Cleanup
on:
  schedule:
    - cron: "20 4 * * sun" # every Sunday at 4:20 AM UTC
  workflow_dispatch:
permissions:
  packages: write
jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@374e2028c8fb93b7219f3771cd405fab95d3dec4
