name: Cleanup Pull Request Images
on:
  pull_request:
    types: [ closed ]
permissions:
  packages: write
jobs:
  ghcr-cleanup-image:
    name: ghcr cleanup action
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Delete image
        uses: dataaxiom/ghcr-cleanup-action@374e2028c8fb93b7219f3771cd405fab95d3dec4
        with:
          delete-tags: pr-${{github.event.pull_request.number}}
