name: Cleanup Pull Request Images
on:
  pull_request:
    types: [ closed ]
permissions:
  packages: write
jobs:
  ghcr-cleanup-image:
    name: ghcr cleanup action
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Delete image
        uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f
        with:
          delete-tags: pr-${{github.event.pull_request.number}}
