name: Cleanup Pull Request Images
on:
  pull_request:
    types: [ closed ]
permissions:
  packages: write
jobs:
  ghcr-cleanup-image:
    name: ghcr cleanup action
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Delete image
        uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f
        with:
          delete-tags: pr-${{github.event.pull_request.number}}
